name: Update Changelog

# Disabled for Registro migration - manual trigger only
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: Update CHANGELOG.md
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main
          fetch-depth: 0

      - name: Update CHANGELOG
        uses: stefanzweifel/changelog-updater-action@14b7eb0468bde47b9f21cd5c9fb8f90ce7769487 # v1.13.1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
        with:
          branch: main
          commit_message: "docs(changelog): update for ${{ github.event.release.tag_name }}"
          file_pattern: CHANGELOG.md
